# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'sangampool'

steps:
- task: Docker@0
  displayName: build
  inputs:
    azureSubscription: 'Free Trial (1d65b7c6-8441-464d-89ce-165ff0e05be0)'
    azureContainerRegistry: '{"loginServer":"sangamlonk.azurecr.io", "id" : "/subscriptions/1d65b7c6-8441-464d-89ce-165ff0e05be0/resourceGroups/container_registry/providers/Microsoft.ContainerRegistry/registries/sangamlonk"}'
    dockerFile: Dockerfile
    imageName: '$(Build.Repository.Name)'

- task: Docker@0
  displayName: 'Push an image'
  inputs:
    azureSubscription: 'Free Trial (1d65b7c6-8441-464d-89ce-165ff0e05be0)'
    azureContainerRegistry: '{"loginServer":"sangamlonk.azurecr.io", "id" : "/subscriptions/1d65b7c6-8441-464d-89ce-165ff0e05be0/resourceGroups/container_registry/providers/Microsoft.ContainerRegistry/registries/sangamlonk"}'
    action: 'Push an image'
    imageName: '$(Build.Repository.Name)'
    includeLatestTag: true

- script: echo Hello, world! > /tmp/sangam.txt
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
