# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'sangampool'

variables:
  dockerId: sangamlonk  # Replace with your Docker ID for Docker Hub or the admin user name for the Azure Container Registry
  imageName: mytestymlimg  # Replace with the name of the image you want to publish

steps:
- script: docker build -t $(dockerId).azurecr.io/$(imageName):$(BUILD_BUILDNUMBER) .  # add options to this command to meet your needs

- script: |
    docker build -t $(dockerId).azurecr.io/$(imageName):$(BUILD_BUILDNUMBER) .
    az login --service-principal -u $(appid) -p $(secretkey) --tenant $(tenant)
    az acr login --name $(dockerId)
    docker push $(dockerId).azurecr.io/$(imageName):$(BUILD_BUILDNUMBER)
  env:
    pswd: $(dockerPassword)        # Define dockerPassword in the Variables tab of this pipeline in Pipelines page of web interface